### ISSUE TITLE
Compatability matrix is not up to date. 

### ISSUE THREAD

**Issue by wlund-pivotal** [spring-projects/spring-boot-data-geode#103]
the wiki page for "Spring Boot for Apache Geode and Pivotal GemFire Version Compatibility Matrix" is not up to date.  It shows 1.3.9.SNAPSHOT on the row for 1.12 geode (the version we need) but start.spring.io correctly shows 1.3.9.RELEASE.

**Comment by jxblum** [comment]
Thanks for bringing this to my attention.  I knew this and I deliberately had not updated the matrix yet for various reasons.

This is correct now!
