### ISSUE TITLE
404 issue with PCC

### ISSUE THREAD

**Issue by ctatineni** [spring-projects/spring-boot-data-geode#15]
Hello,

  trying to test @EnableClusterConfiguration with PCC, i am getting the below exception.

Caused by: org.springframework.web.client.HttpClientErrorException: 404 Not Found
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:79)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:730)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:688)

**Comment by jxblum** [comment]
This is because the [current version of PCC](https://docs.pivotal.io/p-cloud-cache/1-4/index.html#snapshot) does **not** support SDG [{{@EnableClusterConfiguration}} push functionality](https://docs.spring.io/spring-data/geode/docs/current/reference/html/#bootstrap-annotation-config-cluster) just yet.

The Pivotal GemFire team [broke](https://issues.apache.org/jira/projects/GEODE/issues/GEODE-4787) the underlying API on which SDG's {{@EnableClusterConfiguration}} feature is based.

As you can see from the GEODE ticket, the underlying Apache Geode API was restored in version 1.5.0.  Apache Geode v1.5.0 corresponds to Pivotal GemFire 9.4.  PCC currently is based on Pivotal GemFire 9.3.  Therefore, PCC must be upgraded to Pivotal GemFire 9.4+ in order for the Cluster Configuration push functionality to be useable.

**Comment by ranishwetha** [comment]
Hi John,

I am using GemFire 9.1.1, through Pivotal Cloud Cache 1.3.1 and ran into below error -

strong text2018-11-17T16:30:35.279-05:00 [APP/PROC/WEB/0] [OUT] org.springframework.context.ApplicationContextException: Failed to start bean 'gemfireClusterSchemaObjectInitializer'; nested exception is org.apache.geode.cache.client.ServerOperationException: remote server on ac62ca98-0ec5-4a30-606b-1cc9(:8:loner):47710:a6159523:: The function is not registered for function id CreateRegionFunction 2018-11-17T16:30:35.279-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:184)

Finally I ran into this post - https://github.com/spring-projects/spring-boot-data-geode/issues/15

Is there any other annotation I can use with Spring Boot 2+ which can help me with GemFire Region creation, dynamically?

Thanks!

**Comment by jxblum** [comment]
Hi @ranishwetha - Unfortunately, when using PCC 1.3.1, there is no workaround given my [earlier comment](https://github.com/spring-projects/spring-boot-data-geode/issues/15#issuecomment-427154177) above.

We are currently looking into making this work smoothly for the current version of PCC, [1.5](https://docs.pivotal.io/p-cloud-cache/1-5/index.html).  Presently, there is an HTTP authentication error on the client when pushing the cluster configuration (e.g. Region definitions, etc).  As you may already be aware, the cluster config is pushed from the client to the server using the embedded Management REST API, which is served from GemFire/Geode using an embedded HTTP server (currently, Jetty).  This HTTP client connect used to push the config will also need to authenticate.

See GH Issue #16.

Also, would it be possible for you to upgrade to PCC 1.5?

I will report back when I have resolution on Issue #16.

Regards,
@jxblum

**Comment by ranishwetha** [comment]
Thanks John, for the quick response!

We are planning to automate the creation of region, using Spring Annotation API's. Can you please recommend some other alternative, for the current version?

**Comment by jxblum** [comment]
There is no other Spring Annotation or API to help in this case.

Unfortunately, the only option would be to create a _Gfsh_ shell script and run that, manually.  Equally unfortunate, is anytime you add an additional client Region, you have to remember to update your shell script to create that Region on the server.

I will think on this more and get back to you.

**Comment by ranishwetha** [comment]
Great! Thanks John!
