### ISSUE TITLE
Add capability to select a specific user when connecting to Geode

### ISSUE THREAD

**Issue by sboorlagadda** [spring-projects/spring-boot-data-geode#44]
PCC is process of enabling `instance sharing` on PCF, using which one app could gain access to a shared cluster from another `org` and `space`. A new user role `readonly` is introduced with this new feature so that when instances are shared to APPS of other `org` only read-only access is granted.

We need a way to let SBDG apps to work with readonly credentials, this means that the APPS cannot push configuration etc.

In the current state the service key will only have `readonly` user and not other users in the service binding, so rather than asking user to configure which role to pick up it may be as simple as just use existing user from the binding.

**Comment by pulkitpivotal** [comment]
@jxblum Any idea which release this would be included?

**Comment by jxblum** [comment]
@pulkitpivotal - I will include this in SBDG `1.1.1.RELEASE` (the first "service release" for 1.1) as well as SBDG `1.2 M2`.
