### ISSUE TITLE
Auto consume tls_enabled information in VCAP_SERVICES

### ISSUE THREAD

**Issue by waciuma4pivotal** [spring-projects/spring-boot-data-geode#69]
PCC Broker team has completed work so that PCC will include a boolean value for "tls-enabled" in VCAP_SERVICES. It will be included in a future release. This should allow SBDG to move forward on https://github.com/spring-projects/spring-boot-data-geode/issues/61

**Comment by jxblum** [comment]
Thank you @waciuma4pivotal for filing this Issue ticket, however, the required changes as described in #61 have already been made to SBDG.
