### ISSUE TITLE
Improve logging output for @EnableClusterAware functionality re:connection type

### ISSUE THREAD

**Issue by jomartin-999** [spring-projects/spring-boot-data-geode#99]
Currently, when using the `@EnableClusterAware` annotation, it is not trivial to determine if SBDG has connected to the source (cluster) the user is expecting.

To improve the user experience it would be helpful if the dependency, once connected, logged what type of connection it found (ex. none-using local region, standalone, Tanzu GemFire for VMs, Tanzu GemFire for Kubernetes).

**Comment by jxblum** [comment]
Log output is incomplete.

**Comment by jxblum** [comment]
More logging improvements are needed...
